---
#
# Call this task to setup a runit service. 
# Would be best if this task could be shared across roles, not clear
# how to do that at the time of this writing
#
# Required:
# service_name
# service_command (/usr/local/bin/myservice -config /etc/myservice/config
# service_user
#
# Optional:
# service_env_vars - Key Value Hash

- name: runit - create service directories
  file:
    state=directory
    path={{ item }}
    owner=root
    group=root
  with_items:
    - /etc/sv/{{ service_name }}
    - /etc/sv/{{ service_name }}/log
    - /etc/sv/{{ service_name }}/env

- name: runit - main service config
  template:
    src=runit.j2
    dest=/etc/sv/{{ service_name }}/run
    owner=root
    group=root
    mode=0755
  register: a

- name: runit - environmental variables
  lineinfile:
    dest=/etc/sv/{{ service_name }}/env/{{ item.key }}
    line={{ item.value }}
    state=present
    create=yes
    owner=root
    group=root
    mode=0755
  with_dict: service_env_vars|default({})
  register: b

- name: runit - set log config
  template:
    src=runit_log.j2
    dest=/etc/sv/{{ service_name }}/log/run
    owner=root
    group=root
    mode=0755
  register: c

# merely making the directory available in the correct folder will cause runit to run the service
- name: runit - symlink service
  file: src=/etc/sv/{{ service_name }} dest=/etc/service/{{ service_name }} state=link
  register: first_start

- name: runit - Wait for service to start
  wait_for: path=/etc/sv/{{ service_name }}/supervise/ok timeout=7

- name: runit - restart
  runit: name={{ service_name }} state=restarted
  when: first_start.changed == false and (a.changed or b.changed or c.changed)


